# Fix voor OpenSSL 3 'invalid curve name' bug in Fastlane
# OpenSSL::PKey::EC.new werkt niet meer in OpenSSL 3 voor PKCS8 keys
# OpenSSL::PKey.read is de correcte methode in OpenSSL 3
require 'openssl'
module OpenSSL
  module PKey
    class EC
      class << self
        alias_method :_old_new, :new unless method_defined?(:_old_new)
        def new(*args)
          return OpenSSL::PKey.read(*args) if args.first.is_a?(String)
          _old_new(*args)
        rescue OpenSSL::PKey::ECError
          _old_new(*args)
        end
      end
    end
  end
end

default_platform(:ios)

platform :ios do
  desc "Build GlucoDash en upload naar TestFlight"
  lane :build_upload do
    api_key = app_store_connect_api_key(
      key_id: "#{ENV['FASTLANE_KEY_ID']}",
      issuer_id: "#{ENV['FASTLANE_ISSUER_ID']}",
      key_content: "#{ENV['FASTLANE_KEY']}"
    )

    update_code_signing_settings(
      use_automatic_signing: true,
      team_id: ENV["TEAMID"],
      path: "ios/App/App.xcodeproj"
    )

    update_app_identifier(
      xcodeproj: "ios/App/App.xcodeproj",
      plist_path: "App/Info.plist",
      app_identifier: "com.9CGZ7BWVXT.glucodash"
    )

    build_app(
      workspace: "ios/App/App.xcworkspace",
      scheme: "App",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {}
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
